/** ListSurface / ListGroup / ListRow / ListFoot 的样式；写法见 ./css.ts。 */

import { kitSheet } from "./css.ts";

export const listSurfaceSheet = kitSheet(
  [
    "surface",
    "group",
    "groupHead",
    "groupTitle",
    "groupMeta",
    "groupSpacer",
    "groupCount",
    "groupBadges",
    "groupHeadWrap",
    "groupEnd",
    "nested",
    "rows",
    "rowsEmpty",
    "row",
    "rowLeading",
    "rowMain",
    "rowTitleLine",
    "rowTitle",
    "rowTag",
    "rowNote",
    "trailingSpacer",
    "rowBadges",
    "rowSub",
    "rowEnd",
    "rowActions",
    "rowAction",
    "rowChevron",
    "dragHandle",
    "foot",
    "footText",
    "footAction",
  ],
  [
    ".chk_surface{display:flex;flex-direction:column;gap:var(--chk-sp5);min-height:0;flex:none}",
    ".chk_group{display:flex;flex-direction:column;border:1px solid var(--chk-line-weak);border-radius:var(--chk-radius-container);background:var(--chk-surface);overflow:hidden}",
    ".chk_groupHead{display:flex;align-items:center;gap:var(--chk-sp2);padding:0 var(--chk-sp4);min-height:32px;background:var(--chk-surface-sunken);border-bottom:1px solid var(--chk-line-weak)}",
    ".chk_groupTitle{font-size:var(--chk-fs-group);font-weight:500;color:var(--chk-fg-tertiary);white-space:nowrap}",
    ".chk_groupMeta{font-family:var(--chk-mono);font-size:var(--chk-fs-mono);color:var(--chk-fg-caption);min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}",
    ".chk_groupSpacer{flex:1}",
    ".chk_groupCount{font-size:var(--chk-fs-badge);color:var(--chk-fg-caption);font-variant-numeric:tabular-nums;white-space:nowrap}",
    ".chk_groupBadges{display:flex;align-items:center;gap:var(--chk-sp1)}",
    // 可折叠的分组标题行（技能的层级 / 来源仓库、MCP 的「运行中」）：整条是一个按钮。
    ".chk_groupHeadWrap{position:relative;display:flex;align-items:stretch}",
    ".chk_groupHeadWrap>.chk_groupHead{flex:1;min-width:0}",
    ".chk_groupHead[data-fold]{cursor:pointer;width:100%;border:none;border-bottom:1px solid var(--chk-line-weak);font:inherit;text-align:left;color:inherit}",
    ".chk_groupHead[data-fold]:hover{background:var(--chk-hover)}",
    ".chk_groupHead[data-fold]:hover .chk_groupTitle{color:var(--chk-fg-secondary)}",
    ".chk_groupHead[data-fold]:focus-visible{outline:2px solid var(--chk-focus);outline-offset:-2px}",
    ".chk_group[data-collapsed]>.chk_groupHeadWrap>.chk_groupHead,.chk_group[data-collapsed]>.chk_groupHead,.chk_group[data-collapsed]>.chk_groupHeadWrap>.chk_groupEnd{border-bottom:none}",
    ".chk_groupEnd{display:flex;align-items:center;gap:var(--chk-sp2);padding:0 var(--chk-sp3);background:var(--chk-surface-sunken);border-bottom:1px solid var(--chk-line-weak)}",
    ".chk_nested{display:flex;flex-direction:column}",
    // 二级分组：嵌在一级分组里，不再有外框；标题行缩进、用面板底色。
    ".chk_group[data-depth='1']{border:none;border-radius:0;border-top:1px solid var(--chk-line-weak)}",
    ".chk_nested>.chk_group[data-depth='1']:first-child{border-top:none}",
    // 缩进规则：子级内容与父级标题文字对齐（折叠箭头 12px + 间距 8px = 20px 一级）。
    //   一级可折叠分组（技能的层级）：标题文字在 16+20，直接挂在它下面的行也缩到 16+20；
    //   二级分组（来源仓库 / 会话）：标题行缩到 16+20；可折叠的二级分组标题文字在 16+40，它的行缩到 16+40，
    //   不可折叠的二级分组（「运行中」的会话）没有箭头，行与标题文字同在 16+20。
    ".chk_group[data-depth='1']>.chk_groupHead,.chk_group[data-depth='1']>.chk_groupHeadWrap>.chk_groupHead{background:var(--chk-surface);padding-left:calc(var(--chk-sp4) + 20px);min-height:30px}",
    ".chk_group[data-foldable]:not([data-depth])>.chk_rows>.chk_row{padding-left:calc(var(--chk-sp4) + 20px)}",
    ".chk_group[data-depth='1'][data-foldable]>.chk_rows>.chk_row{padding-left:calc(var(--chk-sp4) + 40px)}",
    ".chk_group[data-depth='1']:not([data-foldable])>.chk_rows>.chk_row{padding-left:calc(var(--chk-sp4) + 20px)}",
    ".chk_rows{display:flex;flex-direction:column;margin:0;padding:0;list-style:none}",
    ".chk_rowsEmpty{padding:var(--chk-sp4);font-size:var(--chk-fs-small);color:var(--chk-fg-tertiary)}",
    ".chk_row{position:relative;display:flex;align-items:center;gap:var(--chk-sp3);min-height:var(--chk-row-h);padding:0 var(--chk-sp4);border-top:1px solid var(--chk-line-weak);outline:none}",
    ".chk_row:first-child{border-top:none}",
    ".chk_row[data-openable]{cursor:pointer}",
    ".chk_row[data-openable]:hover{background:var(--chk-hover)}",
    ".chk_row[data-openable]:focus-visible{box-shadow:inset 0 0 0 2px var(--chk-focus)}",
    ".chk_row[data-selected]{background:var(--chk-hover)}",
    ".chk_rowLeading{display:flex;align-items:center;flex:none}",
    ".chk_rowMain{display:flex;flex-direction:column;gap:2px;flex:1;min-width:0}",
    ".chk_rowTitleLine{display:flex;align-items:center;gap:var(--chk-sp2);min-width:0}",
    ".chk_rowTitle{font-size:var(--chk-fs-row-title);font-weight:500;color:var(--chk-fg-primary);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;min-width:0}",
    // 行标题后的目录标签：等宽小字、最弱的说明色，没有边框与底色（比状态标记更弱）。
    // 字号比标题小：行盒与标题同高再下移 1px，让两者的基线大致对齐。
    ".chk_rowTag{flex:none;position:relative;top:1px;font-family:var(--chk-mono);font-size:11px;line-height:20px;color:var(--chk-fg-caption);white-space:nowrap}",
    ".chk_rowBadges{display:flex;align-items:center;gap:var(--chk-sp1);flex:none}",
    ".chk_rowSub{font-size:var(--chk-fs-row-sub);font-weight:400;color:var(--chk-fg-sub);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;min-width:0}",
    ".chk_rowSub[data-mono]{font-family:var(--chk-mono);font-size:var(--chk-fs-mono)}",
    ".chk_rowSub[data-tone=danger]{color:var(--chk-danger)}",
    ".chk_rowSub[data-tone=warn]{color:var(--chk-warn)}",
    ".chk_rowEnd{display:flex;align-items:center;gap:var(--chk-sp3);flex:none}",
    ".chk_rowNote{min-width:64px;text-align:right;font-size:var(--chk-fs-small);line-height:18px;color:var(--chk-fg-secondary);white-space:nowrap;cursor:default}",
    ".chk_rowNote[data-muted]{color:var(--chk-fg-caption)}",
    // 没有开关的行（只读技能）用一个同宽的空位，让行尾文字仍与别的行对齐成一列。
    ".chk_trailingSpacer{flex:none;width:var(--chk-switch-w)}",
    ".chk_rowActions{display:flex;align-items:center;gap:var(--chk-sp2);opacity:0;pointer-events:none;transition:opacity 120ms ease-out}",
    ".chk_row:hover .chk_rowActions,.chk_row:focus-within .chk_rowActions{opacity:1;pointer-events:auto}",
    ".chk_rowAction{cursor:pointer;background:0 0;border:none;border-radius:var(--chk-radius-control);padding:4px 6px;font:inherit;font-size:var(--chk-fs-small);color:var(--chk-fg-secondary)}",
    ".chk_rowAction:hover{background:var(--chk-hover);color:var(--chk-fg-primary)}",
    ".chk_rowAction[data-danger]{color:var(--chk-danger)}",
    ".chk_rowChevron{flex:none;width:12px;text-align:center;font-size:14px;line-height:1;color:var(--chk-fg-caption);opacity:0;transition:opacity 120ms ease-out}",
    ".chk_row:hover .chk_rowChevron,.chk_row:focus-visible .chk_rowChevron{opacity:.75}",
    ".chk_dragHandle{flex:none;display:flex;align-items:center;cursor:grab;color:var(--chk-fg-caption);opacity:0}",
    ".chk_row:hover .chk_dragHandle{opacity:.7}",
    ".chk_row[data-dragging]{opacity:.5}",
    ".chk_foot{display:flex;align-items:center;gap:var(--chk-sp2);flex:none;padding:0 2px}",
    ".chk_footText{font-size:var(--chk-fs-small);color:var(--chk-fg-caption)}",
    ".chk_footAction{cursor:pointer;border:none;background:none;padding:0;font:inherit;font-size:var(--chk-fs-small);color:var(--chk-fg-secondary);text-decoration:underline;text-underline-offset:2px;border-radius:var(--chk-radius-control)}",
    ".chk_footAction:hover{color:var(--chk-fg-primary)}",
    "@media (prefers-reduced-motion:reduce){.chk_rowActions,.chk_rowChevron{transition:none}}",
  ],
);
