/**
 * 技能标签页的字典（D-A3：界面只做中文，标签页字典不需要英文）。
 *
 * 约定：
 *   - key 前缀统一 skills.*（远程部分用 skills.remote.*），避免与其他标签页打架；
 *   - 所有用户可见文案都写在这里，组件里只出现 t("skills.xxx")；
 *   - 宿主返回的诊断 message 已经是中文，直接展示，不进字典；
 *   - UI-A 起：字典里不留死键（test/client-skills/strings.test.ts 双向检查）。
 */

export const zh = {
  /* ---- 通用 ---- */
  "skills.loading": "读取中…",
  "skills.loadFailed": "读取失败：{message}",
  "skills.retry": "重试",
  "skills.cancel": "取消",
  "skills.close": "关闭",
  "skills.crash.title": "技能页渲染失败",
  "skills.crash.hint": "错误已被捕获，其他标签页不受影响：{message}",

  /* ---- 工具栏 ---- */
  "skills.searchPlaceholder": "搜索技能",
  "skills.filterLabel": "筛选",
  "skills.filter.all": "全部",
  "skills.filter.enabled": "已启用",
  "skills.filter.disabled": "已停用",
  "skills.filter.attention": "需关注",
  "skills.addSkill": "添加技能",

  /* ---- 分组与标记 ---- */
  "skills.root.project": "项目级",
  "skills.root.user": "用户级",
  "skills.root.custom": "自定义根",
  "skills.root.dshBuiltin": "DSH 内置",
  "skills.root.bundled": "内置技能",
  "skills.root.writable": "可写",
  "skills.root.readonly": "只读",
  "skills.root.count": "{count} 个",
  "skills.tree.noSource": "无来源",
  "skills.tree.noWorkspace": "当前会话没有工作区，项目级技能目录不可用。",
  "skills.tree.projectEmpty": "当前工作区还没有项目级技能。",
  "skills.tree.levelEmpty": "这里还没有技能。",
  "skills.dirFilter.label": "目录",
  "skills.dirFilter.all": "全部目录",
  "skills.dirFilter.option": "{tag}（{count}）",
  "skills.tag.notLoadable": "不可加载",
  "skills.tag.notLoadableTitle": "frontmatter 不合法或文件格式有问题，DSH 不会加载它。详见详情里的「体检」。",
  "skills.tag.updatable": "可更新",
  "skills.tag.updatableTitle": "上游有新版本。详情里可以更新。",
  "skills.tag.shadowed": "被遮蔽",
  "skills.tag.shadowedTitle": "被更高优先级的 {id} 遮蔽",
  "skills.tag.noName": "无名称",
  "skills.name.hint": "frontmatter 里没有 name，这里显示目录名",
  "skills.toggle.enable": "启用「{name}」",
  "skills.toggle.disable": "停用「{name}」",
  "skills.toggle.blockedReadonly": "只读根，不能启停",
  "skills.toggle.blockedUnsafe": "文件格式不支持安全改写（只能手工改）",

  /* ---- 空状态 ---- */
  "skills.empty.title": "还没有技能",
  "skills.empty.description": "从 GitHub 仓库或 skills.sh 添加。",
  "skills.emptyFiltered.title": "没有符合条件的技能",
  "skills.emptyFiltered.description": "换个关键词，或者把筛选切回「全部」。",

  /* ---- 外部管理提示（D-B11） ---- */
  "skills.warnings.title": "部分技能目录由外部工具管理",

  /* ---- 详情抽屉 ---- */
  "skills.detail.overview": "概览",
  "skills.detail.health": "体检",
  "skills.detail.healthOk": "未发现问题",
  "skills.diag.level.error": "错误",
  "skills.diag.level.warning": "警告",
  "skills.diag.level.info": "提示",
  "skills.detail.skillId": "skillId",
  "skills.detail.path": "位置",
  "skills.detail.root": "根",
  "skills.detail.rootValue": "{root}（{path}，{mode}）",
  "skills.detail.format": "格式",
  "skills.detail.formatValue": "行尾 {eol} · BOM {bom} · {toggle}",
  "skills.detail.eol.lf": "LF",
  "skills.detail.eol.crlf": "CRLF",
  "skills.detail.eol.mixed": "混合",
  "skills.detail.bomYes": "有",
  "skills.detail.bomNo": "无",
  "skills.detail.safeYes": "可安全启停",
  "skills.detail.safeNo": "不可安全改写",
  "skills.detail.visibility": "可见性",
  "skills.detail.yes": "是",
  "skills.detail.no": "否",
  "skills.detail.visibleYes": "模型可见",
  "skills.detail.visibleNo": "模型不可见",
  "skills.detail.userInvocable": "用户可调用",
  "skills.detail.userInvocableNone": "继承默认",
  "skills.detail.extraKeys": "额外 frontmatter 键",
  "skills.detail.mtime": "修改时间",
  "skills.detail.none": "（无）",
  "skills.detail.source": "来源与更新",
  "skills.detail.files": "文件",
  "skills.detail.filesCount": "{count} 项",
  "skills.detail.filesTruncated": "文件清单最多显示 500 项，这里可能不是全部。",
  "skills.detail.content": "SKILL.md",
  "skills.detail.copy": "复制",
  "skills.detail.copied": "已复制",
  "skills.detail.failed": "打开失败：{message}",

  /* ---- 删除确认 ---- */
  "skills.delete.title": "删除技能",
  "skills.delete.body": "「{name}」的整个目录会被移入回收站，之后可以恢复。",
  "skills.delete.bodyFlat": "「{name}」这个技能文件会被移入回收站，之后可以恢复。",
  "skills.delete.lock": "该技能在 npx skills 的 lock 文件里有条目，会随目录一起存入回收站，恢复时放回原处。",
  "skills.delete.button": "删除目录",
  "skills.delete.buttonFlat": "删除文件",
  "skills.delete.confirm": "移入回收站",
  "skills.delete.done": "已把「{name}」移入回收站。",
  "skills.delete.openTrash": "打开回收站",

  /* ---- 回收站抽屉 ---- */
  "skills.trash.title": "回收站",
  "skills.trash.subtitle": "共 {count} 条",
  "skills.trash.empty": "回收站是空的。",
  "skills.trash.rowSub": "{reason} · {time}",
  "skills.trash.originalPath": "原路径：{path}",
  "skills.trash.reason.delete": "删除",
  "skills.trash.reason.update": "更新",
  "skills.trash.reason.replace": "替换",
  "skills.trash.lock": "含 lock 条目",
  "skills.trash.restore": "恢复",
  "skills.trash.purge": "彻底删除",
  "skills.trash.purgeAll": "清空回收站",
  "skills.trash.purgeOne.title": "彻底删除这一条",
  "skills.trash.purgeOne.body": "「{name}」在回收站里的副本会被永久删除，无法再恢复。",
  "skills.trash.purgeAll.title": "清空回收站",
  "skills.trash.purgeAll.body": "回收站里 {count} 条记录会全部被永久删除，无法再恢复。",
  "skills.trash.purgeAck": "我明白这些内容无法再恢复",
  "skills.trash.purgeConfirm": "永久删除",
  "skills.trash.restored": "已恢复「{name}」。",
  "skills.trash.purgedOne": "已从回收站彻底删除 1 条。",
  "skills.trash.purgedAll": "已清空回收站（{count} 条）。",
  "skills.trash.conflict.title": "原路径已存在",
  "skills.trash.conflict.body": "「{path}」已经存在同名内容。继续恢复会把现有内容移入回收站，再用回收站里的版本覆盖它。",
  "skills.trash.conflict.confirm": "覆盖恢复",

  /* ---- 添加技能抽屉 ---- */
  "skills.install.title": "添加技能",
  "skills.install.browse": "浏览",
  "skills.install.browsing": "正在下载并扫描仓库…",
  "skills.install.repoPlaceholder": "owner/name 或 GitHub 链接",
  "skills.install.refPlaceholder": "分支 / 标签",
  "skills.install.repoPreset": "预置",
  "skills.install.browseResults": "仓库内技能",
  "skills.install.selectAll": "全选可安装项",
  "skills.install.installed": "已安装",
  "skills.install.target": "安装到",
  "skills.install.targetUserAgents": "~/.agents/skills",
  "skills.install.targetUserDsh": "~/.dsh/skills",
  "skills.install.targetProjectAgents": "项目级 .agents/skills",
  "skills.install.targetProjectDsh": "项目级 .dsh/skills",
  "skills.install.targetPathUnknown": "路径未知",
  "skills.install.submit": "安装选中技能",
  "skills.install.running": "安装中…",
  "skills.install.ok": "成功",
  "skills.install.failed": "失败",
  "skills.install.resultOk": "已安装：{id}",
  "skills.install.resultFail": "{message}",
  "skills.install.done": "安装完成：成功 {ok} 项，失败 {failed} 项。",

  /* ---- 仓库视图（「添加技能」，D-B16，0.3.0）---- */
  "skills.repoView.subtitle": "汇总仓库列表里的技能；也可以粘贴仓库地址或搜索 skills.sh",
  "skills.repoView.addToList": "加入仓库列表",
  "skills.repoView.inList": "已在列表",
  "skills.repoView.added": "已加入 {repo}：{status}",
  "skills.repoView.repos": "仓库列表",
  "skills.repoView.repoCount": "{count} 个",
  "skills.repoView.edit": "编辑",
  "skills.repoView.remove": "移除",
  "skills.repoView.save": "保存",
  "skills.repoView.cancel": "取消",
  "skills.repoView.subPathPlaceholder": "子目录（可选，如 skills）",
  "skills.repoView.defaultBranch": "默认分支",
  "skills.repoView.wholeRepo": "整个仓库",
  "skills.repoView.notScanned": "未扫描",
  "skills.repoView.scanFailed": "扫描失败",
  "skills.repoView.stale": "分支或子目录已修改，结果是旧的",
  "skills.repoView.skillCount": "{count} 个技能",
  "skills.repoView.searchPlaceholder": "在汇总结果里搜索",
  "skills.repoView.filter.all": "全部",
  "skills.repoView.filter.not": "未安装",
  "skills.repoView.filter.yes": "已安装",
  "skills.repoView.repoAll": "全部仓库",
  "skills.repoView.lastScan": "上次扫描：{time}",
  "skills.repoView.refresh": "刷新",
  "skills.repoView.refreshing": "正在扫描…",
  "skills.repoView.firstScan": "第一次打开，正在扫描仓库列表里的仓库…",
  "skills.repoView.loadFailed": "读取发现结果失败：{message}",
  "skills.repoView.empty": "仓库列表里还没有可发现的技能，加一个仓库试试。",
  "skills.repoView.emptyFiltered": "没有符合条件的技能。",
  "skills.repoView.more": "再显示 {count} 个（共 {total} 个）",
  "skills.repoView.back": "返回汇总",
  "skills.repoView.browsing": "临时浏览：{repo}@{ref}（不在仓库列表里也可以装）",
  "skills.repoView.selected": "已选 {count} 个",
  "skills.repoView.never": "从未",
  "skills.repoView.justNow": "刚刚",
  "skills.repoView.minutesAgo": "{count} 分钟前",
  "skills.repoView.hoursAgo": "{count} 小时前",
  "skills.repoView.daysAgo": "{count} 天前",

  /* ---- 远程 · skills.sh 搜索 ---- */
  "skills.remote.search.placeholder": "搜索 skills.sh（至少 2 个字符）",
  "skills.remote.search.button": "搜索",
  "skills.remote.search.searching": "搜索中…",
  "skills.remote.search.tooShort": "搜索关键词至少需要 2 个字符。",
  "skills.remote.search.results": "搜索结果",
  "skills.remote.search.empty": "没有搜到结果。",
  "skills.remote.search.installs": "安装数 {count}",
  "skills.remote.search.browse": "浏览这个仓库",

  /* ---- 远程 · 来源 ---- */
  "skills.remote.source.origin": "来源",
  "skills.remote.source.loading": "来源读取中…",
  "skills.remote.source.loadFailed": "读取来源失败：{message}",
  "skills.remote.source.title": "{repo} · {path} · 记录于 {store} · 更新于 {updated}",
  "skills.remote.source.store": "记录位置",
  "skills.remote.source.storeLock": ".agents/.skill-lock.json（npx skills）",
  "skills.remote.source.storeHub": "插件记录 sources.json",
  "skills.remote.source.updatedAt": "更新时间",
  "skills.remote.source.orphan": "lock 里有这条记录，但本机已经找不到对应的技能目录。",
  "skills.remote.source.discover": "推测来源",
  "skills.remote.source.discovering": "正在推测…",
  "skills.remote.source.noCandidate": "没有找到候选来源，可以手动登记。",
  "skills.remote.source.register": "登记选中项",
  "skills.remote.source.registered": "已登记来源：{repo}。",
  "skills.remote.source.pickOne": "请先选择一条候选来源。",
  "skills.remote.source.manual": "手动登记",
  "skills.remote.source.unregister": "取消登记",
  "skills.remote.source.unregisterBody": "来源记录会被删除（技能目录本身不动），之后不再能检查更新。",
  "skills.remote.source.unregisterDone": "已取消来源登记。",
  "skills.remote.source.confidence.high": "高置信",
  "skills.remote.source.confidence.medium": "中置信",
  "skills.remote.source.confidence.low": "低置信",

  /* ---- 远程 · 来源表单 ---- */
  "skills.remote.form.repo": "仓库（owner/name 或 GitHub 链接）",
  "skills.remote.form.ref": "分支 / 标签（可留空）",
  "skills.remote.form.skillPath": "仓库内路径（可留空）",
  "skills.remote.form.submit": "登记",
  "skills.remote.form.required": "请填写仓库。",

  /* ---- 远程 · 平铺技能 ---- */
  "skills.remote.flat.unsupported": "平铺 .md 技能不支持来源登记与更新。",

  /* ---- 远程 · 更新 ---- */
  "skills.remote.update.checkOne": "检查更新",
  "skills.remote.update.checking": "检查中…",
  "skills.remote.update.updateOne": "更新",
  "skills.remote.update.updating": "更新中…",
  "skills.remote.update.status.upToDate": "最新",
  "skills.remote.update.status.available": "有更新",
  "skills.remote.update.status.noSource": "无来源",
  "skills.remote.update.status.error": "出错",
  "skills.remote.update.status.unknown": "未检查",
  "skills.remote.update.upToDateHint": "已经是最新版本。",
  "skills.remote.update.availableHint": "上游有新版本，点「更新」会用上游版本覆盖（旧版本进回收站）。",
  "skills.remote.update.noSourceHint": "没有来源记录，无法检查更新。可以先推测或登记来源。",
  "skills.remote.update.trashNote": "旧版本已移入回收站（可恢复），启停状态保持不变。",
  "skills.remote.update.openTrash": "打开回收站",

  /* ---- 远程 · ⋯ 菜单与批量 ---- */
  "skills.remote.menu.checkAll": "检查全部更新",
  "skills.remote.menu.checking": "正在检查…",
  "skills.remote.menu.updateAll": "全部更新（{count}）",
  "skills.remote.menu.applying": "正在更新…",
  "skills.remote.menu.discover": "为无来源技能推测来源",
  "skills.remote.menu.trash": "回收站",
  "skills.remote.menu.trashCount": "回收站（{count}）",
  "skills.remote.menu.auth": "GitHub：{mode} · 剩余配额 {remaining}",
  "skills.remote.menu.authUnknown": "GitHub：{mode} · 剩余配额 未知",
  "skills.remote.menu.workspaceNone": "没有当前会话工作区，不显示项目级技能",
  "skills.remote.quotaUnknownShort": "未知",
  
  "skills.remote.bar.checkSummary": "检查完成：有更新 {available} · 最新 {upToDate} · 无来源 {noSource} · 出错 {error}",
  "skills.remote.bar.updateSummary": "更新完成：成功 {ok} · 失败 {failed}",
  "skills.remote.auth.env": "环境变量 GITHUB_TOKEN",
  "skills.remote.auth.gh": "gh CLI 已登录",
  "skills.remote.auth.anonymous": "匿名（未登录）",
  "skills.remote.auth.unknown": "未知",
  "skills.remote.batch.title": "为无来源技能推测来源",
  "skills.remote.batch.hint": "勾选要登记的候选来源，确认后写入来源记录（不会改动技能内容）。",
  "skills.remote.batch.none": "没有找到候选来源。可以到单个技能的详情里手动登记。",
  "skills.remote.batch.confirm": "登记选中项（{count}）",
  "skills.remote.batch.registerDone": "登记完成：成功 {ok} 项，失败 {failed} 项。",

  /* ---- 操作反馈 ---- */
  "skills.toast.toggleOn": "已启用「{name}」",
  "skills.toast.toggleOff": "已停用「{name}」",
  "skills.toast.failed": "操作失败：{message}",
} as const;

export type SkillsKey = keyof typeof zh;

/** 取一条技能页文案（支持 {name} 模板参数）。界面只做中文，直接返回中文字典。 */
export function t(key: SkillsKey, values?: Record<string, unknown>): string {
  let text: string = zh[key];
  if (values !== undefined) {
    for (const [name, value] of Object.entries(values)) text = text.replaceAll(`{${name}}`, String(value));
  }
  return text;
}
