/**
 * MCP 服务器标签页的字典（D-A3：界面只做中文，标签页字典不需要英文）。
 *
 * 约定：
 *   - key 前缀统一 mcp.*，避免与其他标签页打架；
 *   - 所有用户可见文案都写在这里，组件里只出现 t("mcp.xxx")；
 *   - 宿主返回的校验 message 已经是中文，直接展示，不进字典；
 *   - 页面上的常驻说明长句一律删除（UI-DESIGN §1），说明改放 title 工具提示或抽屉里。
 */

export const zh = {
  /* ---- 通用 ---- */
  "mcp.loadFailed": "读取失败：{message}",
  "mcp.retry": "重试",
  "mcp.cancel": "取消",
  "mcp.close": "关闭",
  "mcp.saving": "保存中…",
  "mcp.edit": "编辑",
  "mcp.delete": "删除",
  "mcp.jsonMode": "JSON 编辑",
  "mcp.crash.title": "MCP 标签渲染失败",
  "mcp.crash.hint": "错误已被捕获，其他标签页不受影响：{message}",
  "mcp.warnings.title": "服务端提示（{count}）",
  "mcp.toast.failed": "操作失败：{message}",

  /* ---- 工具栏（UI-DESIGN §5） ---- */
  "mcp.search": "搜索服务器",
  "mcp.filter.all": "全部",
  "mcp.filter.enabled": "已启用",
  "mcp.filter.disabled": "已停用",
  "mcp.filter.failing": "有错误",
  "mcp.filter.label": "筛选服务器",
  "mcp.add.button": "添加服务器",
  "mcp.add.form": "手动填写",
  "mcp.add.formHint": "逐字段填写",
  "mcp.add.json": "粘贴 JSON",
  "mcp.add.jsonHint": "识别 mcpServers 配置",
  "mcp.add.preset": "预设模板",
  "mcp.add.presetHint": "从常用模板开始",
  "mcp.add.import": "从 Claude Code / Codex 导入",
  "mcp.add.importHint": "只读读取两个来源",
  "mcp.settings.title": "全局设置",

  /* ---- 空 / 加载 ---- */
  "mcp.empty.title": "还没有配置任何 MCP 服务器",
  "mcp.empty.hint": "点「添加服务器」开始：手动填写，或粘贴一段 JSON。",
  "mcp.empty.add": "添加服务器",
  "mcp.empty.filtered": "没有符合当前搜索与筛选的服务器。",

  /* ---- 列表行 ---- */
  "mcp.row.noCommand": "（未设置启动命令）",
  "mcp.row.noUrl": "（未设置地址）",
  "mcp.row.toggleLabel": "启用或停用「{name}」",
  "mcp.row.tools": "· {count} 个工具",
  "mcp.row.badgeFailed": "连接失败",
  "mcp.row.badgeCooling": "冷却中",
  "mcp.row.cooldown": "冷却中，剩余 {remaining}",
  "mcp.row.stateActive": "有活跃实例",
  "mcp.row.stateFailed": "最近失败",
  "mcp.row.stateCooling": "冷却中",
  "mcp.row.dragHint": "拖动可排序",
  "mcp.toast.reordered": "顺序已保存。",
  "mcp.toast.toggleOn": "已启用「{name}」。",
  "mcp.toast.toggleOff": "已停用「{name}」。",

  /* ---- 详情抽屉 ---- */
  "mcp.detail.overview": "概览",
  "mcp.detail.tools": "工具",
  "mcp.detail.secrets": "环境变量与请求头",
  "mcp.detail.failure": "最近失败",
  "mcp.detail.transport": "传输方式",
  "mcp.detail.command": "命令",
  "mcp.detail.url": "地址",
  "mcp.detail.cwd": "工作目录",
  "mcp.detail.lifecycle": "生命周期",
  "mcp.detail.description": "描述",
  "mcp.detail.tags": "标签",
  "mcp.detail.homepage": "主页",
  "mcp.detail.env": "环境变量",
  "mcp.detail.headers": "请求头",
  "mcp.detail.none": "未设置",
  "mcp.detail.refresh": "刷新缓存",
  "mcp.detail.refreshing": "刷新中…",
  "mcp.detail.refreshOk": "「{name}」缓存已刷新：{count} 个工具。",
  "mcp.detail.refreshFailed": "刷新「{name}」失败：{message}",
  "mcp.detail.instances": "运行中的实例",
  "mcp.detail.instancesText": "当前有 {count} 个活跃实例；断开后模型下次调用时会重新连接。",
  "mcp.detail.disconnectAll": "断开全部实例（{count}）",
  "mcp.detail.disconnectOk": "已断开「{name}」的 {count} 个实例。",
  "mcp.detail.disconnectNone": "「{name}」当前没有活跃实例，无需断开。",
  "mcp.detail.disconnectFailed": "断开「{name}」失败：{message}",
  "mcp.detail.cache": "缓存 {count} 个工具 · 更新于 {time}",
  "mcp.detail.cacheStale": "缓存已过期",
  "mcp.detail.noCache": "还没有工具缓存（保存或刷新后会自动探测一次）",
  "mcp.detail.failureTime": "发生在 {time}",
  "mcp.detail.show": "显示",
  "mcp.detail.hide": "隐藏",
  "mcp.detail.revealTitle": "向服务端要明文，只在本次查看里保留",
  "mcp.detail.revealFailed": "读取明文失败：{message}",
  "mcp.detail.revealing": "读取中…",
  "mcp.detail.masked": "已遮罩",
  "mcp.detail.deleteTitle": "删除「{name}」",
  "mcp.detail.jsonTitle": "用 JSON 编辑「{name}」",
  "mcp.detail.editTitle": "编辑「{name}」",

  /* ---- 生命周期 ---- */
  "mcp.lifecycle.lazy": "lazy（首次使用时启动，空闲回收）",
  "mcp.lifecycle.lazy-keep-alive": "lazy-keep-alive（首次使用时启动，会话内常驻）",
  "mcp.lifecycle.eager": "eager（会话开始时启动，空闲回收）",
  "mcp.lifecycle.keep-alive": "keep-alive（会话开始时启动，会话内常驻）",

  /* ---- 表单 ---- */
  "mcp.form.basic": "基础",
  "mcp.form.newTitle": "新建 MCP 服务器",
  "mcp.form.editTitle": "编辑「{name}」",
  "mcp.form.required": "必填",
  "mcp.form.advanced": "高级设置",
  "mcp.form.set": "已设置",
  "mcp.form.reset": "恢复默认",
  "mcp.form.resetTitle": "把这个字段从配置里去掉，回到默认值",
  "mcp.form.save": "保存并生效",
  "mcp.form.saveAnyway": "仍然保存",
  "mcp.form.toJson": "切换到 JSON 编辑",
  "mcp.form.saved": "已生效：「{name}」",
  "mcp.form.savedWithTools": "已生效：「{name}」· 后台探测到 {count} 个工具",
  "mcp.form.probeTimeout": "已保存；后台探测还没返回结果，稍后可在运行态标签查看。",
  "mcp.form.errorCount": "{count} 个字段有问题，请修正后再保存。",
  "mcp.form.serverErrors": "服务端校验未通过（{count} 条）",
  "mcp.form.saveFailed": "保存失败：{message}",
  "mcp.form.unknownField": "未知字段会被服务端拒绝，逐条错误见下。",

  /* ---- 字段：标签 ---- */
  "mcp.field.serverName": "服务器名称",
  "mcp.field.transport": "传输方式",
  "mcp.field.command": "启动命令",
  "mcp.field.args": "启动参数",
  "mcp.field.cwd": "工作目录",
  "mcp.field.env": "环境变量",
  "mcp.field.url": "服务器地址",
  "mcp.field.headers": "请求头",
  "mcp.field.envFrom": "环境变量取值命令（envFrom）",
  "mcp.field.allowEmpty": "允许为空的环境变量（allowEmpty）",
  "mcp.field.envFromTimeoutMs": "取值超时（毫秒）",
  "mcp.field.toolCallTimeoutMs": "工具调用超时（毫秒）",
  "mcp.field.lifecycle": "生命周期",
  "mcp.field.idleTimeout": "空闲回收（分钟）",
  "mcp.field.includeTools": "只暴露这些工具（includeTools）",
  "mcp.field.excludeTools": "排除这些工具（excludeTools）",
  "mcp.field.searchKeywords": "搜索关键词（searchKeywords）",
  "mcp.field.disabled": "停用这个服务器",
  "mcp.field.debug": "调试日志",
  "mcp.field.meta.description": "描述",
  "mcp.field.meta.tags": "标签",
  "mcp.field.meta.homepage": "主页",

  /* ---- 字段：说明 ---- */
  "mcp.hint.serverName": "只能包含字母、数字、下划线、连字符，长度 1–32，且不能与现有服务器重名。",
  "mcp.hint.transport": "stdio = 本地进程；streamable-http = 远程 HTTP 地址。",
  "mcp.hint.command": "例如 node、npx、python。保存时只查 PATH，不执行。",
  "mcp.hint.args": "一行一个参数。默认值：[]",
  "mcp.hint.cwd": "进程的工作目录；不设置用当前目录。",
  "mcp.hint.env": "值默认遮罩为 ***hidden***；点「显示」向服务端要明文，只在本次编辑里保留。",
  "mcp.hint.url": "必须是 http/https 地址。",
  "mcp.hint.headers": "值默认遮罩；没改动的项原样提交，服务端保留原值。",
  "mcp.hint.envFrom": "变量名 → 取值命令；仅 stdio 可用，命令在 cmd.exe 里执行。",
  "mcp.hint.allowEmpty": "必须是 envFrom 里声明过的变量名。默认值：[]",
  "mcp.hint.envFromTimeoutMs": "envFrom 单条命令的超时。默认值：{value}",
  "mcp.hint.toolCallTimeoutMs": "默认值：{value}；≤0 表示不设超时。",
  "mcp.hint.lifecycle": "启动时机 × 回收策略。默认值：lazy",
  "mcp.hint.idleTimeout": "覆盖全局设置；0 = 不回收。默认值：继承全局",
  "mcp.hint.includeTools": "一行一个工具名；留空表示不限制。默认值：不限制",
  "mcp.hint.excludeTools": "一行一个工具名；留空表示不排除。默认值：不排除",
  "mcp.hint.searchKeywords": "工具名 → 关键词（逗号分隔），用于 search 排序。",
  "mcp.hint.disabled": "停用后运行时不启动这个服务器。默认值：启用",
  "mcp.hint.debug": "打开后写更详细的日志。默认值：关闭",
  "mcp.hint.meta.description": "只用于展示。",
  "mcp.hint.meta.tags": "逗号分隔，只用于展示。",
  "mcp.hint.meta.homepage": "只用于展示，点开在浏览器里打开。",

  /* ---- 编辑器原子件 ---- */
  "mcp.editor.add": "添加一项",
  "mcp.editor.remove": "删除这一项",
  "mcp.editor.keyPlaceholder": "名称",
  "mcp.editor.valuePlaceholder": "值",
  "mcp.editor.reveal": "显示",
  "mcp.editor.hide": "隐藏",
  "mcp.editor.revealTitle": "向服务端要明文（只在本次编辑里保留，不会写进回报）",
  "mcp.editor.hidden": "已遮罩",
  "mcp.editor.revealFailed": "读取明文失败：{message}",
  "mcp.editor.revealing": "读取中…",
  "mcp.toast.revealed": "已向服务端取回明文，只在本次查看里保留。",

  /* ---- check-command ---- */
  "mcp.command.check": "检查启动命令",
  "mcp.command.checking": "检查中…",
  "mcp.command.found": "找到启动命令：{path}",
  "mcp.command.missing": "没有找到启动命令「{command}」：它可能没装或不在 PATH 里。仍然可以保存，但服务器可能启动失败。",

  /* ---- JSON 模式 ---- */
  "mcp.json.title": "JSON 编辑「{name}」",
  "mcp.json.newTitle": "JSON 新建服务器",
  "mcp.json.hint": "这里只列显式设置过的字段（默认值不落盘）；敏感值是遮罩后的 ***hidden***，原样提交即保留原值。未知字段会被服务端拒绝。",
  "mcp.json.hiddenWarning": "新建服务器时不要填 ***hidden*** 占位符，它会被当成真实值。",
  "mcp.json.parseError": "JSON 解析失败：{message}",
  "mcp.json.needObject": "顶层必须是一个 JSON 对象（形如 { \"serverName\": \"…\", \"transport\": \"stdio\" }）。",
  "mcp.json.errors": "服务端返回 {count} 条错误",
  "mcp.json.ok": "校验通过。",
  "mcp.json.format": "格式化",
  "mcp.json.save": "校验并保存",
  "mcp.json.toForm": "切换到表单编辑",
  "mcp.json.saveFailed": "保存失败：{message}",

  /* ---- 全局设置（抽屉） ---- */
  "mcp.settings.hint": "所有服务器共用；只保存改过的项，「恢复默认」就从配置里去掉。",
  "mcp.settings.idleTimeout": "空闲回收（分钟）",
  "mcp.settings.idleTimeoutHint": "默认 {value} 分钟；0 = 不回收。",
  "mcp.settings.outputGuard": "输出护栏",
  "mcp.settings.outputGuardHint": "默认开启：{bytes} 字节 / {lines} 行，超出部分落文件。",
  "mcp.settings.outputGuardEnabled": "启用输出护栏",
  "mcp.settings.maxBytes": "最大字节数",
  "mcp.settings.maxBytesHint": "默认 {value} 字节，超出部分落文件。",
  "mcp.settings.maxLines": "最大行数",
  "mcp.settings.maxLinesHint": "默认 {value} 行，超出部分落文件。",
  "mcp.settings.failureBackoffMs": "失败退避（毫秒）",
  "mcp.settings.failureBackoffHint": "默认 {value} 毫秒；失败后这段时间内不再重试。",
  "mcp.settings.save": "保存设置",
  "mcp.settings.saved": "全局设置已保存。",
  "mcp.settings.saveFailed": "设置保存失败：{message}",

  /* ---- 删除确认 ---- */
  "mcp.delete.title": "删除 MCP 服务器",
  "mcp.delete.body": "「{name}」会从配置文件里移除，立即生效。这个操作不可撤销。",
  "mcp.delete.confirm": "确认删除",
  "mcp.delete.cancel": "取消",
  "mcp.delete.done": "已删除「{name}」。",

  /* ---- 粘贴 JSON（D-C2） ---- */
  "mcp.paste.title": "粘贴 MCP 配置（JSON）",
  "mcp.paste.hint": "支持 { \"mcpServers\": { … } }、{ \"servers\": { … } }、「名称 → 服务器对象」映射，或单个服务器对象。识别结果先预览，勾选后才逐个保存。",
  "mcp.paste.placeholder": "{ \"mcpServers\": { \"my-server\": { \"command\": \"npx\", \"args\": [\"-y\", \"pkg\"] } } }",
  "mcp.paste.textLabel": "JSON 内容",
  "mcp.paste.parse": "解析",
  "mcp.paste.parsing": "解析中…",
  "mcp.paste.clear": "清空",
  "mcp.paste.empty": "还没有解析结果：把 JSON 粘到上面的文本框，点「解析」。",
  "mcp.paste.found": "识别出 {count} 个服务器",
  "mcp.paste.warnings": "解析提示（{count}）",
  "mcp.paste.warningRow": "· {text}",
  "mcp.paste.needText": "请先粘贴要解析的 JSON 内容。",
  "mcp.paste.parseFailed": "解析失败（服务端原文）：",
  "mcp.paste.noServers": "没有识别出任何服务器，请检查 JSON 结构。",
  "mcp.paste.statusNew": "可保存",
  "mcp.paste.statusConflict": "同名冲突",
  "mcp.paste.statusInvalid": "名称不合法",
  "mcp.paste.selectRow": "保存「{name}」",
  "mcp.paste.renameLabel": "保存用的名称",
  "mcp.paste.renameHint": "同名时改一个名字即可保存；不改就取消勾选（跳过这个服务器）。",
  "mcp.paste.useSuggested": "用建议名「{name}」",
  "mcp.paste.selected": "已勾选 {count} / {total}",
  "mcp.paste.selectAll": "全选可保存的",
  "mcp.paste.clearSelection": "取消全选",
  "mcp.paste.blocked": "还有 {count} 行勾选了但不能保存：先改名、用建议名，或取消勾选。",
  "mcp.paste.save": "保存勾选的 {count} 个",
  "mcp.paste.saving": "保存中…",
  "mcp.paste.resultSaved": "已保存",
  "mcp.paste.resultFailed": "保存失败：{message}",
  "mcp.paste.savedMany": "已保存 {count} 个服务器，后台正在探测工具数。",
  "mcp.paste.savedNone": "没有任何服务器被保存。",
  "mcp.paste.hiddenWarning": "检测到 ***hidden*** 占位符（{names}）：新建时它会被当成真实值保存，请先替换成真实值。",

  /* ---- 预设模板（D-C2） ---- */
  "mcp.preset.title": "预设模板",
  "mcp.preset.hint": "选一个模板预填表单：可以改完再保存，也可以直接取消。依赖没装时会给出提示。",
  "mcp.preset.loadFailed": "读取预设失败：{message}",
  "mcp.preset.retry": "重试",
  "mcp.preset.empty": "服务端没有返回任何预设。",
  "mcp.preset.use": "用这个模板",
  "mcp.preset.showJson": "查看模板 JSON",
  "mcp.preset.hideJson": "收起模板 JSON",
  "mcp.preset.commandFound": "命令可用：{path}",
  "mcp.preset.commandMissing": "没有找到命令「{command}」，仍可保存，但需要先安装它。",
  "mcp.preset.depends": "模板内容",

  /* ---- 只读导入（D-C2） ---- */
  "mcp.import.title": "从 Claude Code / Codex 导入",
  "mcp.import.hint": "只读读取两个来源的配置（绝不写入它们的文件）。预览确认后逐个导入；同名服务器会被服务端跳过，不覆盖现有配置。",
  "mcp.import.loadFailed": "读取导入来源失败：{message}",
  "mcp.import.retry": "重试",
  "mcp.import.path": "文件路径",
  "mcp.import.notFound": "没有找到这个配置文件。",
  "mcp.import.found": "找到 {count} 个服务器",
  "mcp.import.warnings": "来源提示（{count}）",
  "mcp.import.warningRow": "· {text}",
  "mcp.import.origin": "来源：{origin}",
  "mcp.import.masked": "敏感值已遮罩，导入时由服务端读取原值",
  "mcp.import.selectRow": "导入「{name}」",
  "mcp.import.selected": "已勾选 {count} / {total}",
  "mcp.import.empty": "这个来源里没有可预览的服务器。",
  "mcp.import.apply": "导入勾选的 {count} 个",
  "mcp.import.applying": "导入中…",
  "mcp.import.noSelection": "先勾选要导入的服务器。",
  "mcp.import.imported": "已导入：{names}",
  "mcp.import.skipped": "已跳过（{count}）：",
  "mcp.import.skippedRow": "{name}：{reason}",
  "mcp.import.done": "导入完成：成功 {imported} 个，跳过 {skipped} 个。",
  "mcp.import.failed": "导入失败：{message}",
} as const;

export type McpKey = keyof typeof zh;

/** 取一条 MCP 页文案（支持 {name} 模板参数）。 */
export function t(key: McpKey, values?: Record<string, unknown>): string {
  let text: string = zh[key];
  if (values !== undefined) {
    for (const [name, value] of Object.entries(values)) text = text.replaceAll(`{${name}}`, String(value));
  }
  return text;
}
